### ISSUE TITLE
Support for functions in Javascript class files

### ISSUE THREAD

**Issue by lolbat** [maxgrafik/DocBlockr.novaextension#8]
I am not sure if this is an issue with DocBlockr or JSDocs but in a Javascript class file when I create a doc block for a function it doesn't add a tag with the function name.

```javascript
    /**
     * ￼
     * @param {￼} originalObj - ￼
     */
    copyUnit (originalObj) {

        return JSON.parse(JSON.stringify(originalObj));
        
    }
```

It would be great if it added a `* @function copyUnit` tag to the block

**Comment by maxgrafik** [comment]
Well, this is expected behavior. According to the [JSDoc documentation for classes](https://jsdoc.app/howto-es2015-classes.html) you don't add a `@function` tag. JSDoc should automatically detect your class methods by parsing the code.
If you really want to add a `@function` tag you can always type `@` within a docblock and get a list of tag suggestions.

**Comment by lolbat** [comment]
Well I really should dig into the docs more before I post things. :-(
